Enum for Card Types
evanofslack/pyminion pull request #96
Opened 2023-03-04 23:56 UTC by jaypatel1227

Added a CardTye Enum and replaced all functionality that relied on string card types. Note that since cardType is not yet a module that is a part of pyminion, the examples in bots/examples/ don't work as they can't find pyminion.cardType.

2023-03-16 04:10 UTC, evanofslack requested changes
@jaypatel1227 Thanks for the contribution. I really appreciate you reading through the issues and making this change. I think Enums are much better than just having Strings thrown around.

Looks like all the tests passed, which is great. I just made some comments about some nit picky things. If you can update to address those points it should be good to merge in.

2023-03-16 04:10 UTC, evanofslack commented on pyminion/game.py
> -            elif card.name == "Curse":
This as well should remain a string. Or better yet, copy the above victory card check. 

```python
elif CardType.Curse in card.type:
                basic_piles.append(Pile([card] * CURSE_LENGTH))
```

2023-03-18 15:46 UTC, jaypatel1227 commented on pyminion/cardtype.py
> +"""
moved to the top of core since you use card type in the definition of various Card classes

2023-03-18 15:53 UTC, jaypatel1227 reviewed
Made the changes you requested. Got rid of the cardtype file and rolled it into core.

2023-03-19 03:43 UTC, evanofslack approved these changes

2023-03-19 03:43 UTC, merged

2023-03-19 03:43 UTC, evanofslack commented
Fantastic, thanks @jaypatel1227